// Generated by CoffeeScript 2.2.4
var assign, build, composeMenu, dive, exec, fm, fs, global, globalObj, linkMenu, listFiles, outFilename, outdir, parseFM, path, pretty, pug, readFile, render, run, sortBy, srcdir, writeHtml;

({exec} = require('child_process'));

fs = require('fs');

fm = require('front-matter');

path = require('path');

pug = require('pug');

dive = require('diveSync');

srcdir = './src/pages';

outdir = './out';

pretty = 0;

global = {};

run = function(cmd) {
  return exec(cmd, function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    if (stdout) {
      console.log(`stdout: ${stdout}`);
    }
    if (stderr) {
      return console.log(`stderr: ${stderr}`);
    }
  });
};

listFiles = function(dir = './', list = []) {
  dive(dir, (err, filename) => {
    return list[list.length] = {filename};
  });
  return list;
};

assign = function(action) {
  return function(item) {
    return Object.assign(item, action(item));
  };
};

sortBy = function(property, desc) {
  return function(a, b) {
    return (a[property] > b[property]) ^ desc;
  };
};

outFilename = (item) => {
  return {
    outfile: (item.filename.slice(srcdir.length, -'.pug'.length)).replace(/index$/, '')
  };
};

readFile = (item) => {
  return {
    content: fs.readFileSync(item.filename, 'utf-8')
  };
};

parseFM = (item) => {
  return fm(item.content);
};

globalObj = () => {
  return {global};
};

render = (item) => {
  return {
    html: pug.render(item.body, item)
  };
};

linkMenu = (item) => {
  return Object.assign(item.attributes.menu, {
    path: item.outfile
  });
};

composeMenu = (item) => {
  var base;
  return ((base = item.global).menu != null ? base.menu : base.menu = []).push(item.attributes.menu);
};

writeHtml = (item) => {
  var dir, file;
  dir = path.join(outdir, item.outfile);
  file = path.join(dir, 'index.html');
  run(`mkdir -p ${dir}`);
  return fs.writeFileSync(file, item.html);
};

build = function() {
  var list;
  list = listFiles(srcdir);
  list.map(assign(outFilename));
  list.map(assign(readFile));
  list.map(assign(parseFM));
  list.map(assign(globalObj));
  list.map(linkMenu);
  list.map(composeMenu);
  global.menu.sort(sortBy('order'));
  list.map(assign(render));
  return list.map(writeHtml);
};

//console.log JSON.stringify (list.map (o) => [o.filename, o.outfile]), 0, 4
